In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\Tejas\Jupyter Notebooks\Projects\MLProject-ChurnPrediction-main\tele_churn.csv')

In [3]:
df.head()

Unnamed: 0  SeniorCitizen  MonthlyCharges  TotalCharges  Churn  \
0           0              0           29.85         29.85      0   
1           1              0           56.95       1889.50      0   
2           2              0           53.85        108.15      1   
3           3              0           42.30       1840.75      0   
4           4              0           70.70        151.65      1   

   gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0              1            0           0            1              1  ...   
1              0            1           1            0              1  ...   
2              0            1           1            0              1  ...   
3              0            1           1            0              1  ...   
4              1            0           1            0              1  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  tenure_group_1-12  tenure_group_13-24  \
0                           0                  1                   0   
1                           1                  0                   0   
2                           1                  1                   0   
3                           0                  0                   0   
4                           0                  1                   0   

   tenure_group_25-36  tenure_group_37-48  tenure_group_49-60  \
0                   0                   0                   0   
1                   1                   0                   0   
2                   0                   0                   0   
3                   0                   1                   0   
4                   0                   0                   0   

   tenure_group_61-72  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 52 columns]

In [4]:
df.shape

(7032, 52)

In [5]:
df.columns

Index(['Unnamed: 0', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges',
       'Churn', 'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract

In [6]:
df.drop('Unnamed: 0', inplace=True, axis=1)

In [7]:
df.columns

Index(['SeniorCitizen', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'P

In [8]:
X = df.drop('Churn', axis=1)

In [9]:
X.shape

(7032, 50)

In [10]:
y = df['Churn']

In [11]:
y.shape

(7032,)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [14]:
params = {'criterion':['gini','entropy'], 'max_depth':np.arange(3,15), 'min_samples_leaf': np.arange(4,20,2)}
dtc = DecisionTreeClassifier()

In [15]:
model = GridSearchCV(dtc, params, cv=5, verbose=2)

In [16]:
model.fit(X_train, y_train)

Fitting 5 folds for each of 192 candidates, totalling 960 fits
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=4; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=4; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=4; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=4; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=4; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_samples_leaf=8; total time=   0.0s
[CV] END ....criterion=gini, max_depth=3, min_

[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=12; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=12; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=14; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=14; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=14; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=14; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=14; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=16; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=16; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=16; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=16; total time=   0.0s
[CV] END ...criterion=gini, max_depth=5, min_samples_leaf=16; total time=   0.0s
[CV] END ...criterion=gini, 

[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=6; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=8; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=8; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=8; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=8; total time=   0.0s
[CV] END ....criterion=gini, max_depth=8, min_samples_leaf=8; total time=   0.0s
[CV] END ...criterion=gini, max_depth=8, min_samples_leaf=10; total time=   0.0s
[CV] END ...criterion=gini, max_depth=8, min_samples_leaf=10; total time=   0.0s
[CV] END ...criterion=gini, max_depth=8, min_samples_leaf=10; total time=   0.0s
[CV] END ...criterion=gini, 

[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=14; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=14; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=16; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=16; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=16; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=16; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=16; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=18; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=18; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=18; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=18; total time=   0.0s
[CV] END ..criterion=gini, max_depth=10, min_samples_leaf=18; total time=   0.0s
[CV] END ...criterion=gini, 

[CV] END ...criterion=gini, max_depth=13, min_samples_leaf=8; total time=   0.0s
[CV] END ...criterion=gini, max_depth=13, min_samples_leaf=8; total time=   0.0s
[CV] END ...criterion=gini, max_depth=13, min_samples_leaf=8; total time=   0.0s
[CV] END ...criterion=gini, max_depth=13, min_samples_leaf=8; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=10; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=12; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=12; total time=   0.0s
[CV] END ..criterion=gini, max_depth=13, min_samples_leaf=12; total time=   0.0s
[CV] END ..criterion=gini, m

[CV] END criterion=entropy, max_depth=3, min_samples_leaf=16; total time=   0.0s
[CV] END criterion=entropy, max_depth=3, min_samples_leaf=18; total time=   0.0s
[CV] END criterion=entropy, max_depth=3, min_samples_leaf=18; total time=   0.0s
[CV] END criterion=entropy, max_depth=3, min_samples_leaf=18; total time=   0.0s
[CV] END criterion=entropy, max_depth=3, min_samples_leaf=18; total time=   0.0s
[CV] END criterion=entropy, max_depth=3, min_samples_leaf=18; total time=   0.0s
[CV] END .criterion=entropy, max_depth=4, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=4, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=4, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=4, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=4, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=4, min_samples_leaf=6; total time=   0.0s
[CV] END .criterion=entropy,

[CV] END criterion=entropy, max_depth=6, min_samples_leaf=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=6, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, 

[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=4; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=6; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=6; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=6; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=6; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=6; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=8; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=8; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=8; total time=   0.0s
[CV] END .criterion=entropy, max_depth=9, min_samples_leaf=8; total time=   0.0s
[CV] END .criterion=entropy,

[CV] END criterion=entropy, max_depth=11, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=12; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=14; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=16; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=16; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=16; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=16; total time=   0.0s
[CV] END criterion=entropy, max_depth=11, min_samples_leaf=16; total time=   0.0s
[CV] END criteri

[CV] END criterion=entropy, max_depth=14, min_samples_leaf=4; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=6; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=6; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=6; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=6; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=6; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=8; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=8; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=8; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=8; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=8; total time=   0.0s
[CV] END criterion=entropy, max_depth=14, min_samples_leaf=10; total time=   0.0s
[CV] END criterion=entropy,

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                         'min_samples_leaf': array([ 4,  6,  8, 10, 12, 14, 16, 18])},
             verbose=2)

In [19]:
print(model.best_estimator_)
print(model.best_params_)
print(model.best_score_)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=18)
{'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 18}
0.7966222222222223


In [21]:
dtc_tuned = DecisionTreeClassifier(criterion='gini', max_depth=5, min_samples_leaf=18)

In [22]:
dtc_tuned.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=18)

In [23]:
y_pred = dtc_tuned.predict(X_test)

In [24]:
import sys
np.set_printoptions(threshold=sys.maxsize)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,

In [25]:
y_test = y_test.to_numpy()
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [27]:
print(confusion_matrix(y_test, y_pred))

[[921 117]
 [181 188]]


In [28]:
print(accuracy_score(y_test, y_pred))

0.7882018479033405


In [29]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1038
           1       0.62      0.51      0.56       369

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407



In [30]:
#upsampling using smoteenn
from imblearn.combine import SMOTEENN
sm = SMOTEENN()

In [31]:
X_resampled, y_resampled = sm.fit_resample(X,y)

In [32]:
Xr_train, Xr_test, yr_train, yr_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=0)

In [33]:
dtc_resampled = DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_leaf=8)

In [34]:
dtc_resampled.fit(Xr_train, yr_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_leaf=8)

In [35]:
yr_pred = dtc_resampled.predict(Xr_test)

In [36]:
print(confusion_matrix(yr_test, yr_pred))

[[478  51]
 [ 32 613]]


In [37]:
print(accuracy_score(yr_test, yr_pred))

0.9293015332197615


In [38]:
print(dtc_resampled.score(Xr_test, yr_test))

0.9293015332197615


In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
rf_model = RandomForestClassifier(n_estimators = 100, criterion='entropy', max_depth=6, min_samples_leaf=8)

In [41]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_leaf=8)

In [42]:
y_pred = rf_model.predict(X_test)


In [43]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.93      0.87      1038
           1       0.68      0.43      0.53       369

    accuracy                           0.80      1407
   macro avg       0.75      0.68      0.70      1407
weighted avg       0.78      0.80      0.78      1407



In [44]:
#upsampling with randomForestClassifier
rf_resampled = RandomForestClassifier(n_estimators = 100, criterion='gini', max_depth=6, min_samples_leaf=8)
rf_resampled.fit(Xr_train, yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8)

In [45]:
yr_rf_pred = rf_resampled.predict(Xr_test)

In [46]:
print(accuracy_score(yr_rf_pred, yr_test))
print(classification_report(yr_test, yr_rf_pred))

0.9293015332197615
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       529
           1       0.93      0.94      0.94       645

    accuracy                           0.93      1174
   macro avg       0.93      0.93      0.93      1174
weighted avg       0.93      0.93      0.93      1174



In [47]:
print(confusion_matrix(yr_test, yr_rf_pred))

[[483  46]
 [ 37 608]]


In [48]:
#trying principal component analysis
from sklearn.decomposition import PCA
pca = PCA(0.9)
Xr_train_pca = pca.fit_transform(Xr_train)
Xr_test_pca = pca.transform(Xr_test)
explained_variance = pca.explained_variance_ratio_

In [49]:
pca_rf_model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [50]:
pca_rf_model.fit(Xr_train_pca, yr_train)
yr_pred_pca = pca_rf_model.predict(Xr_test_pca)

In [51]:
print(accuracy_score(yr_pred_pca, yr_test))
print(classification_report(yr_test, yr_pred_pca))

0.7291311754684838
              precision    recall  f1-score   support

           0       0.72      0.64      0.68       529
           1       0.73      0.80      0.76       645

    accuracy                           0.73      1174
   macro avg       0.73      0.72      0.72      1174
weighted avg       0.73      0.73      0.73      1174



In [53]:
#pickling
import pickle

In [54]:
filename = 'model.sav'

In [56]:
pickle.dump(rf_resampled, open(filename, 'wb'))

In [59]:
load_model = pickle.load(open(filename, 'rb'))

In [60]:
load_model.score(Xr_test, yr_test)

0.9293015332197615